[package]
name = "project1"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.23", default-features = false, features = ["rustls-tls", "blocking"]}
url = "2.5.4"
dirs = "6.0.0"